// Self-contained review of reserved transport land and explicit connections.
import fs from 'node:fs/promises'
import path from 'node:path'
import { proposedBandLand } from '../../src/objects/bandLand'
import { proposedBandExpressway } from '../../src/objects/bandExpresswayLand'
import { expressJourney, planBandTransport } from '../../src/objects/bandExpressway'
import { bandGraph, planBandStreets, type BandPoint, type BandStreetPlan } from '../../src/objects/bandStreetPlan'

const out=process.env.OUTPUT_DIR
if(!out||!path.isAbsolute(out))throw Error('OUTPUT_DIR must be absolute')
await fs.mkdir(out,{recursive:true})
const site=proposedBandLand(),before=planBandStreets(site),start=performance.now(),plan=planBandTransport(site,proposedBandExpressway()),elapsed=performance.now()-start
const fast=plan.expressway,after=plan.surface
const summary=(p:BandStreetPlan)=>({segments:p.roads.length,components:bandGraph(p.roads).components,centres:p.site.centres.length,unconnected:p.unconnected,unallocatedDemand:p.unallocatedDemand,accessLinks:p.accessLinks})
const report={generated:new Date().toISOString(),scope:'land reservation and directed road planning only; not applied to the 3D app',elapsedMs:elapsed,
  before:summary(before),after:summary(after),interchanges:fast.interchanges.length,junctions:1,junctionBranchRamps:fast.edges.filter(e=>e.kind==='jct-ramp').length,
  mainlineKm:fast.design.routes[0].points.slice(1).reduce((s,p,i)=>s+Math.hypot(p[0]-fast.design.routes[0].points[i][0],p[1]-fast.design.routes[0].points[i][1]),0)/1000,
  bridges:fast.bridges,underpasses:fast.surfaceSite.crossings.filter(c=>c.mode==='underpass'),gradeSeparatedCrossings:plan.crossings.filter(c=>!c.transfer).length,
  transferCrossings:plan.crossings.filter(c=>c.transfer).length}
const journeys=Object.fromEntries(['open','closed'].map(state=>[state,Object.fromEntries(fast.interchanges.flatMap(a=>fast.interchanges.map(b=>[`${a.id}|${b.id}`,expressJourney(fast,a.node,b.node,state==='closed'?[fast.junction.id]:[])])))]))
await fs.writeFile(path.join(out,'plan.json'),JSON.stringify({report,plan,journeys},null,2))
await fs.writeFile(path.join(out,'summary.json'),JSON.stringify(report,null,2))
const pt=(p:BandPoint)=>`${p[1].toFixed(3)},${(-p[0]).toFixed(3)}`
const d=(points:BandPoint[])=>points.map((p,i)=>(i?'L':'M')+pt(p)).join(' ')
const esc=(s:string)=>s.replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('"','&quot;')
const json=(v:unknown)=>JSON.stringify(v).replaceAll('<','\\u003c')
const colours={water:'#bad0d4',green:'#cfddbd',facility:'#e1cdbc',transport:'#e1d8eb'}
const land=(p:BandStreetPlan)=>p.site.reserves.map(r=>`<path class="land ${r.kind}" d="${d(r.polygon)}Z" fill="${colours[r.kind]}"/>`).join('')
const ground=(p:BandStreetPlan)=>p.roads.map(r=>`<path class="road ${r.kind}${r.underpass?' underpass':''}${r.bridge?' water-bridge':''}" d="${d([r.from,r.to])}"/>`).join('')
const centres=site.centres.map(c=>`<circle class="district" cx="${c.point[1]}" cy="${-c.point[0]}" r="23"><title>${esc(c.id)}</title></circle>`).join('')
const express=fast.edges.map(e=>`<path class="express ${e.kind} ${e.structure}" data-owner="${e.owner}" data-edge="${esc(e.id)}" d="${d(e.points)}"/>`).join('')
const bridge=fast.bridges.map(b=>`<path class="bridge-reservation" d="${d([b.from,b.to])}"/>`).join('')
const passages=fast.surfaceSite.crossings.filter(c=>c.mode==='underpass').map(c=>{
  const p:BandPoint=[(c.from[0]+c.to[0])/2,(c.from[1]+c.to[1])/2]
  return `<g class="passage"><path class="passage-casing" d="${d([c.from,c.to])}"/><path class="road underpass" d="${d([c.from,c.to])}"/><text x="${p[1]+150}" y="${-p[0]+125}">一般道は下を通過</text></g>`
}).join('')
const bridgeNotes=fast.bridges.map(b=>`<text class="bridge-note" x="${b.from[1]+160}" y="${-(b.from[0]+b.to[0])/2+25}">専用道橋の予約</text>`).join('')
const movements=fast.edges.filter(e=>e.kind==='jct-ramp').map(e=>{
  const from=fast.nodes.find(n=>n.id===e.from)!,to=fast.nodes.find(n=>n.id===e.to)!
  return {id:e.id,label:e.from.startsWith(fast.junction.branch)?`物流支線 → ${to.point[1]>fast.junction.point[1]?'北':'南'}方面`:`${from.point[1]<fast.junction.point[1]?'南':'北'}方面 → 物流支線`}
})
const gates=fast.interchanges.map(ic=>`<g class="gate"><circle cx="${ic.gate[1]}" cy="${-ic.gate[0]}" r="38"/><text x="${ic.gate[1]+60}" y="${-ic.gate[0]+140}">${ic.name}</text></g>`).join('')
const jct=`<g class="jct"><path d="M${pt([fast.junction.point[0]+52,fast.junction.point[1]])}l52 52 -52 52 -52 -52Z"/><text x="${fast.junction.point[1]+80}" y="${-fast.junction.point[0]-130}">${fast.junction.name}</text></g>`
const defs='<defs><marker id="arrow" viewBox="0 0 10 10" refX="8" refY="5" markerWidth="5" markerHeight="5" orient="auto-start-reverse"><path d="M0 0L10 5L0 10Z" fill="#c15a29"/></marker></defs>'
const frame=`<rect x="${-site.length/2}" y="${-site.width/2}" width="${site.length}" height="${site.width}" fill="#f7f5ed"/>`
const extent=[-site.length/2,-site.width/2,site.length,site.width].join(' ')
const svg=(id:string,content:string,detail=false)=>`<svg id="${id}" class="${detail?'detail':'overview'}" viewBox="${extent}" role="img" aria-label="${id}">${defs}${frame}${content}<g class="journey"></g><g class="map-scale"></g></svg>`
const general=land(before)+ground(before)+centres,newContent=land(after)+ground(after)+centres+passages+express+bridge+gates+jct+bridgeNotes
const gateOptions=fast.interchanges.map(i=>`<option value="${i.id}">${i.name}</option>`).join('')
const html=`<!doctype html><html lang="ja"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Spinward — 専用道路とJCTの土地計画</title>
<style>*{box-sizing:border-box}body{margin:0;background:#eeece4;color:#293c3d;font:15px/1.65 system-ui,sans-serif}main{max-width:1440px;margin:auto;padding:28px}h1{font-size:28px;line-height:1.4;margin:8px 0}h2{font-size:17px;margin:0 0 8px}p{margin:8px 0}.eyebrow{color:#766888;letter-spacing:.14em;font-size:12px}.note{color:#63716f;max-width:1080px}.controls{display:flex;flex-wrap:wrap;gap:16px;align-items:center;padding:16px;background:#fffdf8;border-radius:10px;margin:18px 0}select,button{font:inherit;padding:7px;border:1px solid #b9c2bc;border-radius:5px;background:white}label{display:flex;gap:8px;align-items:center}.legend{display:flex;flex-wrap:wrap;gap:18px;font-size:13px}.legend span:before{content:'';display:inline-block;width:17px;height:9px;background:var(--c);margin-right:6px}article{margin:14px 0;padding:16px;background:#fffdf8;border:1px solid #d6d8ce;border-radius:10px}.overview{display:block;width:100%;height:115px}.detail{display:block;width:100%;height:550px}.road,.express,.bridge-reservation{fill:none;vector-effect:non-scaling-stroke;stroke-linecap:round;stroke-linejoin:round}.arterial{stroke:#506e68;stroke-width:1.6}.collector{stroke:#94a299;stroke-width:.8}.water-bridge{stroke:#769692;stroke-width:2}.underpass{stroke:#087c84;stroke-width:2}.express{stroke:#795398;stroke-width:2}.ic-ramp,.jct-ramp{stroke-width:2.1}.flyover{paint-order:stroke;filter:drop-shadow(0 1px 1px #fffdf8)}.bridge-reservation{stroke:#ae89c3;stroke-width:7;stroke-dasharray:3 3;pointer-events:none}.district{fill:#4c6863}.gate circle{fill:#fffdf8;stroke:#396c61;stroke-width:2;vector-effect:non-scaling-stroke}.gate text,.jct text{font-size:74px;paint-order:stroke;stroke:#fffdf8;stroke-width:20;fill:#263f37}.jct path{fill:#795398;stroke:white;stroke-width:2;vector-effect:non-scaling-stroke}.jct text{fill:#694087}.overview .gate text,.overview .jct text{display:none}.overview .express{stroke-width:2.1}.overview .collector{stroke-width:.6}.overview .bridge-reservation{stroke-width:4}.journey path{fill:none;stroke:#c15a29;stroke-width:3;vector-effect:non-scaling-stroke;marker-end:url(#arrow)}.overview .journey path{stroke-width:2.3;marker-end:none}.closed .jct-ramp{stroke:#b0a9b5;stroke-dasharray:5 5}.hide-local .collector{display:none}.hide-reserves .transport{display:none}.compare{display:grid;grid-template-columns:1fr 1fr;gap:16px}.status{background:#f1ebdf;border-left:4px solid #c15a29;padding:12px 16px;margin:12px 0;min-height:76px}.status p{margin:0}.status strong{font-size:17px}.metrics{color:#6c577d;font-size:13px}#focus-name{color:#795398}button{cursor:pointer}button:hover{background:#f4ecf8}@media(max-width:850px){main{padding:16px}.compare{grid-template-columns:1fr}.detail{height:420px}h1{font-size:23px}.controls{gap:10px}}</style>
<main><div class="eyebrow">SPINWARD / LAND BAND 01 / TRANSPORT RESERVATION</div><h1>生活の道と、遠くへ行く道をつなぐ</h1><p class="note">東縁を走る約39.2kmの本線と南端物流支線。一般道との出入りはIC、専用道路同士の分岐・合流はJCTへ集約します。用地と接続を検討する計画図で、現在の3D体験には未反映です。</p>
<style>.passage-casing{fill:none;stroke:#fffdf8;stroke-width:5;vector-effect:non-scaling-stroke}.passage text,.bridge-note{font-size:70px;fill:#246b70;paint-order:stroke;stroke:#fffdf8;stroke-width:22}.bridge-note{fill:#77518c}.overview .passage text,.overview .bridge-note{display:none}.connections{margin:14px 0;padding:14px 16px;background:#fffdf8;border:1px solid #d6d8ce;border-radius:10px}.movement-buttons{display:flex;flex-wrap:wrap;gap:8px;margin:8px 0}.movement-buttons button{font-size:13px;color:#684588}.movement-buttons button[aria-pressed=true]{background:#efe0cc;color:#a04520;border-color:#c15a29}.movement-buttons button:disabled{color:#918d94;text-decoration:line-through;cursor:default}.connection-note{font-size:13px;color:#626f6c}.state-badge{display:inline-block;font-size:13px;padding:2px 8px;margin-left:8px;border-radius:4px;background:#e4eee5;color:#2b614a}.closed .state-badge{background:#f4ddd6;color:#943b32}.detail .journey path{stroke-width:2.5}.direction{display:flex;justify-content:space-between;font-size:12px;color:#687a71;margin-top:4px}</style>
<div class="legend"><span style="--c:#795398">専用道路・ランプ</span><span style="--c:#e1d8eb">専用道路の確保用地</span><span style="--c:#506e68">一般道の幹線</span><span style="--c:#94a299">集散道路</span><span style="--c:#087c84">一般道の立体横断</span><span style="--c:#c15a29">選択した専用道経路</span></div>
<div class="controls"><label>出発 <select id="from">${gateOptions}</select></label><label>到着 <select id="to">${gateOptions}</select></label><label>JCT <select id="junction"><option value="open">分岐・合流を開通</option><option value="closed">物流支線との接続を閉鎖</option></select></label><label><input type="checkbox" id="local" checked>集散道路</label><label><input type="checkbox" id="reserves" checked>確保用地</label></div>
<div id="journey-status" class="status" role="status"></div>
<article><h2>専用道路なしの一般道 <small>同じ39.84km × 3.15km</small></h2>${svg('before-overview',general)}</article>
<article><h2>専用道路の用地・IC接続を加えた新案</h2>${svg('after-overview',newContent)}<p class="metrics">本線1本・支線1本 / IC 7か所（端部の3か所を含む） / JCT 1か所・分岐合流ランプ4本 / 専用道の渡河予約1か所 / 一般道の立体横断候補5か所</p></article>
<div class="controls"><label>拡大地点 <select id="focus"><option value="jct">南部物流 JCT</option><option value="arrival">到着地区 IC</option><option value="bridge">物流支線の渡河</option><option value="north">北端 IC</option></select></label><button id="swap">出発と到着を入れ替える</button><span id="focus-name"></span></div>
<div class="connections"><strong>南部物流JCTの4方向の分岐・合流</strong><span class="state-badge" id="jct-state"></span><div class="movement-buttons">${movements.map((m,i)=>`<button data-movement="${i}" aria-pressed="false">${m.label}</button>`).join('')}<button id="show-journey">旅行経路を表示</button></div><p class="connection-note">方向を選ぶと、そのランプだけを詳細図で強調します。本線の南→北・北→南の通過は、JCT閉鎖中も維持します。<span id="movement-state"></span></p></div>
<div class="compare"><article><h2>一般道のみ / 同じ範囲</h2><p class="connection-note">専用道路を予約する前の一般道</p>${svg('before-detail',general,true)}<div class="direction"><span>← 南端方向</span><span>北端方向 →</span></div></article><article><h2>新案 / <span id="detail-label">南部物流 JCT</span><span class="state-badge" id="detail-state"></span></h2><p class="connection-note" id="detail-movement"></p>${svg('after-detail',newContent,true)}<div class="direction"><span>← 南端方向</span><span>北端方向 →</span></div></article></div><p class="connection-note" id="focus-description"></p>
<p class="note">JCTの閉鎖は専用支線への4本のランプに作用します。本線の直進と一般道は残り、物流地区への一般道の経路まで消えるわけではありません。橙色は専用道路だけの経路で、出発・到着IC以外の一般道には降りません。</p><p class="note">ICの白丸が一般道との接続点。図の交差だけでは接続せず、一般道の通過路は専用道路をくぐる想定です。ランプの線は候補形状で、上下線の離隔・縦断勾配・桁下高・合流長・曲率・柱・道路幅を含む立体設計は未完了です。幹線と集散道路の先に、住宅路地・敷地・建物を生成します。</p><p class="note">川筋・地区・施設・道路の配置はSpinwardの独自案です。元の格子の出口は引き継いでいません。現在の3Dの地形、交通、案内、遠景、残る2居住帯への適用はこれからです。</p></main>
<script>
const journeys=${json(journeys)},edges=${json(Object.fromEntries(fast.edges.map(e=>[e.id,{d:d(e.points),kind:e.kind}])) )},names=${json(Object.fromEntries(fast.interchanges.map(i=>[i.id,i.name])))},extent=${json([site.length,site.width])};
const movements=${json(movements)};let selectedMovement=-1;
const focuses={jct:{pos:-18100,span:3640,label:'南部物流 JCT',note:'本線の双方向通過 ＋ 物流支線との4方向の分岐・合流'},arrival:{pos:1600,span:3000,label:'到着地区 IC',note:'4本のランプが一般道の接続点へ集まる'},bridge:{pos:-18800,span:2240,label:'物流支線の渡河',note:'支線の渡河用地と、南端物流への接続'},north:{pos:18700,span:2440,label:'北端 IC',note:'本線の端を一般道への出入りで終える'}};
const q=s=>document.querySelector(s);q('#from').value='port-terminal';q('#to').value='arrival-ic';
function draw(){const closed=q('#junction').value==='closed',from=q('#from').value,to=q('#to').value,j=journeys[closed?'closed':'open'][from+'|'+to];document.body.classList.toggle('closed',closed);document.body.classList.toggle('hide-local',!q('#local').checked);document.body.classList.toggle('hide-reserves',!q('#reserves').checked);for(const id of ['after-overview','after-detail'])q('#'+id+' .journey').innerHTML=j?j.edges.map(id=>'<path d="'+edges[id].d+'"/>').join(''):'';
q('#jct-state').textContent=closed?'物流接続：閉鎖':'物流接続：開通';q('#detail-state').textContent=closed?'JCT物流接続：閉鎖':'JCT物流接続：開通';document.querySelectorAll('[data-movement]').forEach(b=>{b.disabled=closed;b.setAttribute('aria-pressed',String(+b.dataset.movement===selectedMovement))});q('#movement-state').textContent=selectedMovement<0?' 現在は旅行経路を表示。':' 現在の強調：'+movements[selectedMovement].label+(closed?'（閉鎖）':'');if(selectedMovement>=0)q('#after-detail .journey').innerHTML=closed?'':'<path d="'+edges[movements[selectedMovement].id].d+'"/>';
q('#detail-movement').textContent=selectedMovement<0?'経路：'+names[from]+' → '+names[to]+(j?'':'（専用道では到達不可）'):'ランプ：'+movements[selectedMovement].label+(closed?'（閉鎖）':'');
q('#journey-status').innerHTML='<strong>'+names[from]+' → '+names[to]+'</strong><p>'+(from===to?'同じICです。別の到着地点を選ぶと経路を表示します。':j?'専用道路の経路 '+(j.length/1000).toFixed(2)+' km'+(j.edges.some(id=>edges[id].kind==='jct-ramp')?' · 南部物流JCTを経由':' · 本線を通過'):'専用道路だけでは到達できません。JCTを閉鎖しても一般道は接続しています。')+'</p>';
const f=focuses[q('#focus').value],pos=Math.max(-extent[0]/2+f.span/2,Math.min(extent[0]/2-f.span/2,f.pos));q('#detail-label').textContent=f.label;q('#focus-name').textContent=f.note;
q('#focus-description').textContent=q('#focus').value==='arrival'?'到着地区ICの白丸から一般道へ接続し、到着地区・東岸住宅・旧市街へ向かいます。紫は専用道路、緑は一般道、薄紫は確保用地です。':q('#focus').value==='north'?'北端ICは一般道を介して北端物流・北部住宅へ接続します。白丸が一般道との転送点です。':'白丸＝ICの一般道接続点、菱形＝JCTの位置、灰色破線＝閉鎖したランプ。専用支線と一般道は立体交差し、一般道は下を通ります。';
for(const id of ['before-detail','after-detail']){const svg=q('#'+id);svg.setAttribute('viewBox',[pos-f.span/2,-extent[1]/2,f.span,extent[1]].join(' '));svg.querySelector('.map-scale').innerHTML='<path d="M'+(pos-f.span/2+140)+','+(extent[1]/2-170)+'h500" fill="none" stroke="#36584e" stroke-width="2" vector-effect="non-scaling-stroke"/><text x="'+(pos-f.span/2+140)+'" y="'+(extent[1]/2-235)+'" font-size="75" fill="#36584e">500 m</text>';}
for(const id of ['before-overview','after-overview']){const svg=q('#'+id);svg.querySelector('.focus-box')?.remove();svg.insertAdjacentHTML('beforeend','<rect class="focus-box" x="'+(pos-f.span/2)+'" y="'+(-extent[1]/2)+'" width="'+f.span+'" height="'+extent[1]+'" fill="none" stroke="#a97142" stroke-width="2" stroke-dasharray="5 4" vector-effect="non-scaling-stroke"/>');}}
document.querySelectorAll('select,input').forEach(e=>e.addEventListener('change',draw));q('#swap').addEventListener('click',()=>{const v=q('#from').value;q('#from').value=q('#to').value;q('#to').value=v;draw()});draw();
document.querySelectorAll('[data-movement]').forEach(b=>b.addEventListener('click',()=>{selectedMovement=+b.dataset.movement;q('#focus').value='jct';draw()}));q('#show-journey').addEventListener('click',()=>{selectedMovement=-1;draw()});q('#focus').addEventListener('change',()=>{selectedMovement=-1;draw()});
</script></html>`
await fs.writeFile(path.join(out,'map.html'),html)
console.log(JSON.stringify(report,null,2))
