import {probeForecourts} from './forecourt-probe.mjs';
import {probeBalconies} from './balcony-probe.mjs';
import {probeStairs} from './stair-probe.mjs';
import {probeWindowLights} from './window-light-probe.mjs';
const {chromium}=await import(process.env.PLAYWRIGHT_MODULE??'playwright');
import fs from 'node:fs';import {fileURLToPath} from 'node:url';import * as T from 'three';
const out=fileURLToPath(new URL('.',import.meta.url)),base=process.env.SPINWARD_URL??'https://127.0.0.1:5192';
const time=process.env.TIME??'.42',prefix=process.env.PREFIX??'colony-use';
const browser=await chromium.launch({channel:'chrome',headless:true});
try{const reports=[];for(const scene of (process.env.SCENES??'apartments,mixed,mixed-street,office,commercial,commercial-street').split(',')){
 const page=await browser.newPage({ignoreHTTPSErrors:true,viewport:{width:1600,height:1000}}),errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error'&&/shader|WebGLProgram/.test(m.text()))errors.push(m.text())});
 if(process.env.FALLBACK)await page.route('**/colony-modules.glb',route=>route.abort());
 await page.goto(base+'/?debug&visit=city-block&rpm=0&t='+time,{waitUntil:'domcontentloaded',timeout:60000});await page.waitForSelector('#splash',{state:'detached'});
 const target=await page.evaluate(({scene,forecourt,balcony,requested,stairs,windows,officeStyle})=>{
  const c=window.__spinwardCity;
  if(scene==='roof'){const roofs=c.beacons.userData.mounts;return {roof:roofs[Math.floor(roofs.length/3)]}}
  const entries=c.colonyBuildings.entries.filter(e=>!e.interior&&(scene.startsWith('mixed')?e.design.use.primary==='apartments'&&e.design.use.mixed:scene.startsWith('office')?e.design.use.primary==='office'&&e.design.use.ground==='lobby':scene.startsWith('commercial')?e.design.use.primary==='commercial':e.design.use.primary==='apartments'&&e.design.use.ground==='residential'&&e.spec.building.height>18)&&e.spec.building.width>16&&(scene!=='commercial-street'||e.spec.building.kind==='block'));
  const selected=requested?c.colonyBuildings.entries.filter(e=>!e.interior&&Math.abs(e.spec.building.azimuth-requested[0])<1e-8&&Math.abs(e.spec.building.axial-requested[1])<1e-6):stairs?c.colonyBuildings.entries.filter(e=>c.colonyBuildings.stairwells.get(e.spec.building)?.kind===stairs):forecourt?entries.filter(e=>c.colonyBuildings.forecourts.has(e.spec.building)):officeStyle?entries.filter(e=>(e.design.profile.paneBottom<.1)===(officeStyle==='full')):entries;
  selected.sort((e,f)=>Math.hypot((e.spec.building.azimuth-.05)*3200,e.spec.building.axial)-Math.hypot((f.spec.building.azimuth-.05)*3200,f.spec.building.axial));if(!selected.length)throw Error('No representative for '+scene);return {b:selected[0].spec.building,use:selected[0].design.use,...(forecourt||balcony||stairs||windows?{matrix:selected[0].matrix.elements}:{}),...(stairs?{stair:c.colonyBuildings.stairwells.get(selected[0].spec.building)}:{}),...(windows?{windowFace:[...selected[0].spec.volumes].sort((a,b)=>windows==='rear'?(a.z-a.d/2)-(b.z-b.d/2):b.z+b.d/2-a.z-a.d/2)[0],profile:selected[0].design.profile}:{}),...(balcony?{balconyFace:[...selected[0].spec.volumes].sort((a,b)=>b.z+b.d/2-a.z-a.d/2)[0]}:{}),...(forecourt?{planters:c.colonyBuildings.forecourts.get(selected[0].spec.building)}:{})}
 },{scene,forecourt:!!process.env.FORECOURTS,balcony:!!process.env.BALCONIES,stairs:process.env.STAIRS,windows:process.env.WINDOWS,officeStyle:process.env.OFFICE_STYLE,requested:process.env.TARGET?.split(',').map(Number)});
 let pos,aim,up;
 if(target.windowFace){const matrix=new T.Matrix4().fromArray(target.matrix),v=target.windowFace,side=process.env.WINDOWS==='rear'?-1:1,y=v.y-v.h/2+Math.min(v.h*.4,12),z=v.z+side*v.d/2;pos=new T.Vector3(v.x+Math.min(v.w*.15,2),y+1,z+side*(side<0?4:10)).applyMatrix4(matrix);aim=new T.Vector3(v.x,y,z).applyMatrix4(matrix);up=new T.Vector3(0,1,0).transformDirection(matrix)}
 else if(target.stair){const matrix=new T.Matrix4().fromArray(target.matrix),s=target.stair,x=s.x-(s.kind==='external'?2.45:0),y=Math.min(s.levels.at(-1)*.55,14);pos=new T.Vector3(x+(process.env.STAIR_REVERSE?-8:8),y+2,s.z-(process.env.STAIR_REVERSE?16:12)).applyMatrix4(matrix);aim=new T.Vector3(x,y,s.z-1).applyMatrix4(matrix);up=new T.Vector3(0,1,0).transformDirection(matrix)}
 else if(target.balconyFace){const matrix=new T.Matrix4().fromArray(target.matrix),v=target.balconyFace,y=Math.min(v.h*.45,12),z=v.z+v.d/2;pos=new T.Vector3(v.x+v.w*.2,y+1,z+9).applyMatrix4(matrix);aim=new T.Vector3(v.x,y,z).applyMatrix4(matrix);up=new T.Vector3(0,1,0).transformDirection(matrix)}
 else if(target.planters){const matrix=new T.Matrix4().fromArray(target.matrix),x=target.planters.reduce((n,p)=>n+p.x,0)/target.planters.length,z=target.planters[0].z;pos=new T.Vector3(x+4.5,2.2,z+3).applyMatrix4(matrix);aim=new T.Vector3(x,1.15,z-.15).applyMatrix4(matrix);up=new T.Vector3(0,1,0).transformDirection(matrix)}
 else if(target.roof){const r=target.roof;up=new T.Vector3(r.up.x,r.up.y,r.up.z);const across=new T.Vector3(-up.z,0,up.x);pos=new T.Vector3(r.x,r.y,r.z).addScaledVector(up,4).addScaledVector(across,7);aim=new T.Vector3(r.x,r.y,r.z).addScaledVector(up,.3)}
 else{const b=target.b,a=b.access.roadEdge.azimuth+(b.front.axis==='axial'?(scene.endsWith('street')?12:35)/3200:b.front.side*10/3200),ax=b.access.roadEdge.axial+(b.front.axis==='tangent'?(scene.endsWith('street')?12:35):b.front.side*10);up=new T.Vector3(-Math.cos(a),0,-Math.sin(a));pos=new T.Vector3(Math.cos(a)*(scene.endsWith('street')?3197.6:3185),ax,Math.sin(a)*(scene.endsWith('street')?3197.6:3185));aim=new T.Vector3(Math.cos(b.azimuth)*(scene.endsWith('street')?3197:3192),b.axial,Math.sin(b.azimuth)*(scene.endsWith('street')?3197:3192))}
 const q=new T.Quaternion().setFromRotationMatrix(new T.Matrix4().lookAt(pos,aim,up));await page.goto(base+`/?debug&stats&m=f&p=${pos.toArray()}&q=${q.toArray()}&rpm=0&t=${time}&dpr=1`,{waitUntil:'domcontentloaded',timeout:60000});await page.waitForSelector('#splash',{state:'detached'});await page.waitForFunction(fallback=>(fallback||window.__spinwardCity.colonyBuildings.group.userData.asset)&&window.__spinwardCity.authoredBlock.group.userData.buildings.every(b=>b.asset),!!process.env.FALLBACK);await page.waitForTimeout(800);
 if(process.env.WINDOWS)await page.waitForFunction(()=>window.__spinward.mode==='free-fly',null,{timeout:5000});
 const data=await page.evaluate(()=>{const c=window.__spinwardCity,lights=c.beacons,stems=c.beaconStems;const near=c.colonyBuildings.entries.filter(e=>e.visible).slice(0,1000);return {detail:c.colonyBuildings.group.userData,useCounts:c.colonyBuildings.entries.reduce((n,e)=>{const k=e.design.use.primary+'/'+e.design.use.ground;n[k]=(n[k]??0)+1;return n},{}),stats:document.querySelector('.stats-overlay')?.textContent,paintCount:new Set(near.map(e=>e.design.wall)).size,profileCount:new Set(near.map(e=>JSON.stringify(e.design.profile))).size,lights:lights.count,stems:stems.count,visibleLights:lights.userData.visible.filter(Boolean).length,attachmentMismatch:lights.userData.mounts.some((r,i)=>{const a=stems.userData.baseMatrices;return Math.hypot(a[i*16+12]-(r.x+r.up.x*.175),a[i*16+13]-(r.y+r.up.y*.175),a[i*16+14]-(r.z+r.up.z*.175))>.005})}});
 if(process.env.FORECOURTS)data.forecourts=await page.evaluate(probeForecourts);
 data.balconyAlignment=await page.evaluate(probeBalconies);
 data.stairAlignment=await page.evaluate(probeStairs);
 if(process.env.WINDOWS){const source=fs.readFileSync(new URL('../../src/objects/colonyWindowAppearance.ts',import.meta.url),'utf8').match(/export const COLONY_WINDOW_GLSL=`([\s\S]*?)`/)[1];data.windowLights=await page.evaluate(probeWindowLights,source)}
 data.frames=await page.evaluate(async()=>{const samples=[];let last=performance.now(),start=last;await new Promise(resolve=>{const frame=now=>{samples.push(now-last);last=now;if(now-start<3000)requestAnimationFrame(frame);else resolve()};requestAnimationFrame(frame)});samples.shift();samples.sort((a,b)=>a-b);const gl=[...document.querySelectorAll('canvas')].map(c=>c.getContext('webgl2')).find(Boolean),ext=gl?.getExtension('WEBGL_debug_renderer_info');return {renderer:ext?gl.getParameter(ext.UNMASKED_RENDERER_WEBGL):'unknown',median:samples[Math.floor(samples.length*.5)],p95:samples[Math.floor(samples.length*.95)]}});
 if(data.attachmentMismatch||data.lights!==data.stems||errors.length)throw Error(JSON.stringify({data,errors}));await page.evaluate(()=>{document.querySelector('.lil-gui')?.remove();const panels=[];window.__spinwardScene.traverse(o=>{if(o.renderOrder===30)panels.push(o)});panels.forEach(o=>o.removeFromParent())});await page.screenshot({path:out+prefix+'-'+scene+'.png'});reports.push({scene,time,url:page.url(),target,...data,errors});console.log(JSON.stringify(reports.at(-1)));fs.writeFileSync(out+prefix+'.json',JSON.stringify(reports,null,2));await page.close();
}}finally{await browser.close()}
